#include "buddy_chars.h"

/* ============================================================
 * Cat  —  curvy ears, whiskers, tail
 * ============================================================ */

/* SLEEP (2 frames) — closed eyes */
static const char *const cat_sleep[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     /\\_/\\        ",
        "    ( -.- )       ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "      Zzz         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "    ( - - )       ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "    Zzz           ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* IDLE (2 frames) — open eyes alternating */
static const char *const cat_idle[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     /\\_/\\        ",
        "    ( o.o )       ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "    ( O.O )       ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* BUSY (2 frames) — working hard */
static const char *const cat_busy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     /\\_/\\   `    ",
        "    ( >_< )       ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   [working...]   ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\   `    ",
        "    ( x.x )  '    ",
        "     > ^ <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "  [thinking..]    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* ATTENTION (2 frames) — alert */
static const char *const cat_attention[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     /\\_/\\        ",
        "    ( @.@ )       ",
        "     > ! <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "    ( @.@ )!      ",
        "     > ! <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* CELEBRATE (3 frames) — happy */
static const char *const cat_celebrate[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "  ^  /\\_/\\  ^     ",
        "    ( ^o^ )       ",
        "     > w <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   \\o/ YAY!       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "   ( ^o^  )  *    ",
        "     > w <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   APPROVED!      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\   *    ",
        "    (^o^)         ",
        "     > w <   *    ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   \\o/ YAY!       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* DIZZY (3 frames) — spinning */
static const char *const cat_dizzy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     /\\_/\\        ",
        "   ( @_@ )        ",
        "    > ~ <          ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   whoaaa...      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "    (@_@ )         ",
        "     > ~ <         ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "    ...uuugh      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\        ",
        "    ( @_@)         ",
        "     > ~ <         ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   spinning...    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* HEART (2 frames) — love */
static const char *const cat_heart[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "    <3/\\_/\\       ",
        "    ( *.* )       ",
        "     > <3         ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "   <3 <3 <3       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     /\\_/\\  <3    ",
        "    ( *.* )       ",
        "    <3 > <        ",
        "    /|   |\\       ",
        "   (_|   |_)      ",
        "                  ",
        "    <3 <3 <3      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* ============================================================
 * Duck  —  round body, flat beak
 * ============================================================ */

static const char *const duck_sleep[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      ___         ",
        "     ( -.-)       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "      Zzz         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___         ",
        "     ( - -)       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "    Zzz           ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_idle[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      ___         ",
        "     ( o.o)       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___         ",
        "     ( O.O)       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_busy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      ___    `    ",
        "     (>_< )       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   [quack...]     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___   '     ",
        "     (x.x )       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   [waddling..]   ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_attention[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      ___         ",
        "     (@.@ )       ",
        "     <!!>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___         ",
        "     ( @.@)!      ",
        "     <!!>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_celebrate[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "  ^   ___   ^     ",
        "     (^o^ )       ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   QUACK!!        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___   *     ",
        "    (^o^  )  *    ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   APPROVED!      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ___          ",
        "    ( ^o^)   *    ",
        "     <__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   QUACK!!        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_dizzy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      ___         ",
        "    (@_@ )         ",
        "     <~>           ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   wobble...      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___         ",
        "     (@_@)         ",
        "     <~>           ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   ...quack?      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___         ",
        "    ( @_@)         ",
        "     <~>           ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   spinning...    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const duck_heart[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "   <3 ___         ",
        "     (*.* )       ",
        "    <3__>         ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "   <3 <3 <3       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      ___  <3     ",
        "     (*.* )       ",
        "     <__<3        ",
        "    (_____)       ",
        "     |   |        ",
        "                  ",
        "    <3 <3 <3      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* ============================================================
 * Penguin  —  tuxedo body, flippers
 * ============================================================ */

static const char *const penguin_sleep[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     ( )          ",
        "    ( -.-)         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "      Zzz         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    ( - -)         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "    Zzz           ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_idle[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     ( )          ",
        "    ( o.o)         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    ( O.O)         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_busy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     ( )     `    ",
        "    (>_< )         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "  [waddling...]   ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )    '     ",
        "    (x.x )         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   [fishing..]    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_attention[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     ( )          ",
        "    (@.@ )         ",
        "   /|!  !\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    ( @.@)!       ",
        "   /|!  !\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_celebrate[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "  ^  ( )  ^       ",
        "    (^o^ )         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   NOOT NOOT!     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )   *      ",
        "   (^o^ )    *    ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   APPROVED!      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    (^o^ )  *     ",
        "   /|   |\\   *    ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   NOOT NOOT!     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_dizzy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     ( )          ",
        "   (@_@ )          ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   sliding...     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    (@_@)          ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   ...noot?       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( )          ",
        "    ( @_@)         ",
        "   /|   |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   whoa ice...    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const penguin_heart[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "  <3 ( )          ",
        "    (*.* )         ",
        "   /|<3 |\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "   <3 <3 <3       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     ( ) <3       ",
        "    (*.* )         ",
        "   /| <3|\\        ",
        "  / |___| \\       ",
        "    |   |         ",
        "    \"   \"         ",
        "    <3 <3 <3      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* ============================================================
 * Robot  —  boxy head, antenna, panel body
 * ============================================================ */

static const char *const robot_sleep[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      [ ]         ",
        "     [-.- ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "      Zzz         ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]         ",
        "     [- - ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "    Zzz           ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_idle[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      [ ]         ",
        "     [o.o ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]         ",
        "     [O.O ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_busy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      [ ]    `    ",
        "     [>_< ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "  [computing..]   ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]   '     ",
        "     [x.x ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "  [analyzing..]   ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_attention[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "     [!][ ]       ",
        "     [@.@ ]       ",
        "    [_____]       ",
        "     | ! |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ][!]      ",
        "     [@.@ ]!      ",
        "    [_____]       ",
        "     | ! |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "  !! PROMPT !!    ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_celebrate[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "   *  [ ]  *      ",
        "     [^o^ ]       ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   BEEP BOOP!     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]   *     ",
        "   [ ^o^ ]  *     ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   APPROVED!      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "     *[ ]*        ",
        "    [ ^o^]        ",
        "    [_____]       ",
        "     |   |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   BEEP BOOP!     ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_dizzy[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "      [ ]         ",
        "   [ @_@ ]        ",
        "    [_____]       ",
        "     | ~ |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   ERROR...       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]         ",
        "    [@_@ ]         ",
        "    [_____]       ",
        "     | ~ |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   ...BZZT        ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ]         ",
        "     [@_@]         ",
        "    [_____]       ",
        "     | ~ |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   REBOOT...      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

static const char *const robot_heart[MAX_ANIM_FRAMES][BUDDY_FRAME_LINES] = {
    {
        "   <3 [ ]         ",
        "     [*.* ]       ",
        "    [_____]       ",
        "     |<3 |        ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "   <3 <3 <3       ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
    {
        "      [ ] <3      ",
        "     [*.* ]       ",
        "     |<3 |        ",
        "    [_____]       ",
        "    [=   =]       ",
        "     |   |        ",
        "   [__|__]        ",
        "    <3 <3 <3      ",
        "                  ",
        "                  ",
        "                  ",
        "                  ",
    },
};

/* ============================================================
 * Species registry
 * ============================================================ */

const buddy_species_t BUDDY_SPECIES[] = {
    {
        .name = "Cat",
        .personality = "Curious and playful",
        .state_frames = { &cat_sleep, &cat_idle, &cat_busy, &cat_attention, &cat_celebrate, &cat_dizzy, &cat_heart },
        .frame_count = { 2, 2, 2, 2, 3, 3, 2 },
    },
    {
        .name = "Duck",
        .personality = "Cheerful and waddly",
        .state_frames = { &duck_sleep, &duck_idle, &duck_busy, &duck_attention, &duck_celebrate, &duck_dizzy, &duck_heart },
        .frame_count = { 2, 2, 2, 2, 3, 3, 2 },
    },
    {
        .name = "Penguin",
        .personality = "Cool and collected",
        .state_frames = { &penguin_sleep, &penguin_idle, &penguin_busy, &penguin_attention, &penguin_celebrate, &penguin_dizzy, &penguin_heart },
        .frame_count = { 2, 2, 2, 2, 3, 3, 2 },
    },
    {
        .name = "Robot",
        .personality = "Logical and helpful",
        .state_frames = { &robot_sleep, &robot_idle, &robot_busy, &robot_attention, &robot_celebrate, &robot_dizzy, &robot_heart },
        .frame_count = { 2, 2, 2, 2, 3, 3, 2 },
    },
};

const int BUDDY_SPECIES_COUNT = sizeof(BUDDY_SPECIES) / sizeof(BUDDY_SPECIES[0]);
