"""Color theme definitions (dark and light)."""

THEMES = {
    "dark": {
        "bg": "#1e1e1e",
        "panel": "#252526",
        "card": "#1a1a1a",
        "text": "#e0e0e0",
        "text_dim": "#aaa",
        "text_muted": "#888",
        "hdr_bg": "#333333",
        "hdr_fg": "#ffffff",
        "cell_fg": "#d4d4d4",
        "input_bg": "#3c3c3c",
        "input_fg": "#e0e0e0",
        "btn_bg": "#444",
        "btn_fg": "#ccc",
        "btn_primary": "#3a6ea5",
        "btn_green": "#2d7d46",
        "sel_border": "#4fc3f7",
        "sel_bg": "#3a6ea5",
        "ctrl_fg": "#666",
        "err_fg": "#f66",
        "border": "#444",
        "list_bg": "#1e1e1e",
        "list_fg": "#cccccc",
        "progress": "#3a6ea5",
        "preview_bg": "#1a1a1a",
        "preview_img_bg": (26, 26, 26, 255),
        "preview_fg": (255, 255, 255, 255),
        "btn_accent_fg": "white",
        "title_fg": "#ffffff",
    },
    "light": {
        "bg": "#f0f0f0",
        "panel": "#e8e8e8",
        "card": "#ffffff",
        "text": "#1a1a1a",
        "text_dim": "#555",
        "text_muted": "#777",
        "hdr_bg": "#d0d0d0",
        "hdr_fg": "#1a1a1a",
        "cell_fg": "#222222",
        "input_bg": "#ffffff",
        "input_fg": "#1a1a1a",
        "btn_bg": "#ccc",
        "btn_fg": "#333",
        "btn_primary": "#3a6ea5",
        "btn_green": "#2d7d46",
        "sel_border": "#1a6ea5",
        "sel_bg": "#3a6ea5",
        "ctrl_fg": "#999",
        "err_fg": "#d32f2f",
        "border": "#bbb",
        "list_bg": "#ffffff",
        "list_fg": "#333333",
        "progress": "#3a6ea5",
        "preview_bg": "#ffffff",
        "preview_img_bg": (255, 255, 255, 255),
        "preview_fg": (0, 0, 0, 255),
        "btn_accent_fg": "#1a1a1a",
        "title_fg": "#1a1a1a",
    },
}
